# Generated by Django 4.1.7 on 2023-04-02 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('studentId', models.CharField(max_length=50)),
                ('hasOutstandingBalance', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=8, unique=True)),
                ('amount', models.FloatField(max_length=50)),
                ('dueDate', models.DateTimeField(max_length=50)),
                ('status', models.CharField(choices=[('O', 'OUTSTANDING'), ('P', 'PAID'), ('C', 'CANCELLED')], max_length=50)),
                ('type', models.CharField(choices=[('L', 'LIBRARY FINES'), ('T', 'TUITION FEES')], max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.account')),
            ],
        ),
    ]
